class Park < ActiveHash::Base
 self.data = [
   { id: 1, name: 'トランジットスチーマーライン（メディテレーニアンハーバー発）', category: 'attraction', area:'mediterranean_harbor' },
   { id: 2, name: 'ソアリン：ファンタスティック・フライト' , category: 'attraction', area:'mediterranean_harbor', dpa: true },
   { id: 3, name: 'フォートレス・エクスプロレーション' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 4, name: 'ヴェネツィアン・ゴンドラ' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 5, name: 'ザ・レオナルドチャレンジ' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 6, name: 'タートル・トーク', category: 'attraction', area:'american_waterfront', pp: true },
   { id: 7, name: 'タワー・オブ・テラー', category: 'attraction', area:'american_waterfront', dpa: true },
   { id: 8, name: 'エレクトリックレールウェイ（アメリカンウォーターフロント発）', category: 'attraction', area:'american_waterfront' },
   { id: 9, name: 'トランジットスチーマーライン（一周）（アメリカンウォーターフロント発）', category: 'attraction', area:'american_waterfront' },
   { id: 10, name: 'トイ・ストーリー・マニア！', category: 'attraction', area:'american_waterfront', dpa: true },
   { id: 11, name: 'ビッグシティ・ヴィークル', category: 'attraction', area:'american_waterfront' },
   { id: 12, name: 'アクアトピア', category: 'attraction', area:'port_discovery' },
   { id: 13, name: 'エレクトリックレールウェイ（ポートディスカバリー発）', category: 'attraction', area:'port_discovery' },
   { id: 14, name: 'ニモ＆フレンズ・シーライダー', category: 'attraction', area:'port_discovery',  pp: true },
   { id: 15, name: 'インディ・ジョーンズ', category: 'attraction', area:'lost_river_delta', pp: true },
   { id: 16, name: 'トランジットスチーマーライン（ロストリバーデルタ発）', category: 'attraction', area:'lost_river_delta' },
   { id: 17, name: 'レイジングスピリッツ', category: 'attraction', area:'lost_river_delta', pp: true },
   { id: 18, name: 'アナとエルサのフローズンジャーニー', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 19, name: 'ラプンツェルのランタンフェスティバル', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 20, name: 'ピーターパンのネバーランドアドベンチャー', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 21, name: 'フェアリー・ティンカーベルのビジーバギー', category: 'attraction', area:'fantasy_springs' },
   { id: 22, name: 'キャラバンカルーセル', category: 'attraction', area:'arabian_coast' },
   { id: 23, name: 'ジャスミンのフライングカーペット', category: 'attraction', area:'arabian_coast' },
   { id: 24, name: 'シンドバッド・ストーリーブック・ヴォヤッジ', category: 'attraction', area:'arabian_coast' },
   { id: 25, name: 'マジックランプシアター', category: 'attraction', area:'arabian_coast', pp: true },
   { id: 26, name: 'アリエルのプレイグラウンド', category: 'attraction', area:'mermaid_lagoon' },
   { id: 27, name: 'ジャンピン・ジェリーフィッシュ', category: 'attraction', area:'mermaid_lagoon' },
   { id: 28, name: 'スカットルのスクーター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 29, name: 'フランダーのフライングフィッシュコースター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 30, name: 'ブローフィッシュ・バルーンレース', category: 'attraction', area:'mermaid_lagoon' },
   { id: 31, name: 'マーメイドラグーンシアター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 32, name: 'ワールプール', category: 'attraction', area:'mermaid_lagoon' },
   { id: 33, name: '海底2万マイル', category: 'attraction', area:'port_discovery', pp: true },
   { id: 34, name: 'センター・オブ・ジ・アース', category: 'attraction', area:'port_discovery', dpa: true },

   { id: 5, name: 'スターブライト・クリスマス（花火）' , category: 'parade', area:'park_wide' },
   { id: 6, name: 'ダッフィー＆フレンズのカラフルハピネスジャーニー', category: 'parade', area:'park_wide' },
   { id: 6, name: 'ディズニー・クリスマス・グリーティング', category: 'parade', area:'mediterranean_harbor' },
   { id: 6, name: 'ビリーブ！～シー・オブ・ドリームス～', category: 'parade', area:'mediterranean_harbor' },

   { id: 6, name: 'ドリームス・テイク・フライト', category: 'show', area:'american_waterfront', dpa: true, entry_request: true },

   { id: 5, name: 'ザ・レオナルドチャレンジ' , category: 'restaurant', area:'mediterranean_harbor' },
   { id: 6, name: 'タートル・トーク', category: 'restaurant', area:'american_waterfront', pp: true },
 ]
end