class Target < ActiveHash::Base
 self.data = [
  #アトラクション
   { id: 1, name: 'トランジットスチーマーライン（メディテレーニアンハーバー発）', category: 'attraction', area:'mediterranean_harbor' },
   { id: 2, name: 'ソアリン：ファンタスティック・フライト' , category: 'attraction', area:'mediterranean_harbor', dpa: true },
   { id: 3, name: 'フォートレス・エクスプロレーション' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 4, name: 'ヴェネツィアン・ゴンドラ' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 5, name: 'ザ・レオナルドチャレンジ' , category: 'attraction', area:'mediterranean_harbor' },
   { id: 6, name: 'タートル・トーク', category: 'attraction', area:'american_waterfront', pp: true },
   { id: 7, name: 'タワー・オブ・テラー', category: 'attraction', area:'american_waterfront', dpa: true },
   { id: 8, name: 'エレクトリックレールウェイ（アメリカンウォーターフロント発）', category: 'attraction', area:'american_waterfront' },
   { id: 9, name: 'トランジットスチーマーライン（一周）（アメリカンウォーターフロント発）', category: 'attraction', area:'american_waterfront' },
   { id: 10, name: 'トイ・ストーリー・マニア！', category: 'attraction', area:'american_waterfront', dpa: true },
   { id: 11, name: 'ビッグシティ・ヴィークル', category: 'attraction', area:'american_waterfront' },
   { id: 12, name: 'アクアトピア', category: 'attraction', area:'port_discovery' },
   { id: 13, name: 'エレクトリックレールウェイ（ポートディスカバリー発）', category: 'attraction', area:'port_discovery' },
   { id: 14, name: 'ニモ＆フレンズ・シーライダー', category: 'attraction', area:'port_discovery',  pp: true },
   { id: 15, name: 'インディ・ジョーンズ', category: 'attraction', area:'lost_river_delta', pp: true },
   { id: 16, name: 'トランジットスチーマーライン（ロストリバーデルタ発）', category: 'attraction', area:'lost_river_delta' },
   { id: 17, name: 'レイジングスピリッツ', category: 'attraction', area:'lost_river_delta', pp: true },
   { id: 18, name: 'アナとエルサのフローズンジャーニー', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 19, name: 'ラプンツェルのランタンフェスティバル', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 20, name: 'ピーターパンのネバーランドアドベンチャー', category: 'attraction', area:'fantasy_springs', dpa: true },
   { id: 21, name: 'フェアリー・ティンカーベルのビジーバギー', category: 'attraction', area:'fantasy_springs' },
   { id: 22, name: 'キャラバンカルーセル', category: 'attraction', area:'arabian_coast' },
   { id: 23, name: 'ジャスミンのフライングカーペット', category: 'attraction', area:'arabian_coast' },
   { id: 24, name: 'シンドバッド・ストーリーブック・ヴォヤッジ', category: 'attraction', area:'arabian_coast' },
   { id: 25, name: 'マジックランプシアター', category: 'attraction', area:'arabian_coast', pp: true },
   { id: 26, name: 'アリエルのプレイグラウンド', category: 'attraction', area:'mermaid_lagoon' },
   { id: 27, name: 'ジャンピン・ジェリーフィッシュ', category: 'attraction', area:'mermaid_lagoon' },
   { id: 28, name: 'スカットルのスクーター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 29, name: 'フランダーのフライングフィッシュコースター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 30, name: 'ブローフィッシュ・バルーンレース', category: 'attraction', area:'mermaid_lagoon' },
   { id: 31, name: 'マーメイドラグーンシアター', category: 'attraction', area:'mermaid_lagoon' },
   { id: 32, name: 'ワールプール', category: 'attraction', area:'mermaid_lagoon' },
   { id: 33, name: '海底2万マイル', category: 'attraction', area:'mysterious_island', pp: true },
   { id: 34, name: 'センター・オブ・ジ・アース', category: 'attraction', area:'mysterious_island', dpa: true },

   #パレード
   { id: 35, name: 'スターブライト・クリスマス（花火）' , category: 'parade', area:'park_wide' },
   { id: 36, name: 'ダッフィー＆フレンズのカラフルハピネスジャーニー', category: 'parade', area:'park_wide' },
   { id: 37, name: 'ディズニー・クリスマス・グリーティング', category: 'parade', area:'mediterranean_harbor' },
   { id: 38, name: 'ビリーブ！～シー・オブ・ドリームス～', category: 'parade', area:'mediterranean_harbor' },

   #ショー
   { id: 39, name: 'ドリームス・テイク・フライト', category: 'show', area:'american_waterfront', dpa: true, entry_request: true },

   #レストラン
   { id: 40, name: 'カフェ・ポルトフィーノ' , category: 'restaurant', area:'mediterranean_harbor' },
   { id: 41, name: 'ゴンドリエ・スナック', category: 'restaurant', area:'mediterranean_harbor'},
   { id: 42, name: 'ザンビーニ・ブラザーズ・リストランテ', category: 'restaurant', area:'mediterranean_harbor', mobile_order: true },
   { id: 43, name: 'マゼランズ', category: 'restaurant', area:'mediterranean_harbor' },
   { id: 44, name: 'マンマ・ビスコティーズ・ベーカリー', category: 'restaurant', area:'mediterranean_harbor' },
   { id: 45, name: 'リストランテ・ディ・カナレット', category: 'restaurant', area:'mediterranean_harbor' },
   { id: 46, name: 'リフレスコス', category: 'restaurant', area:'mediterranean_harbor', mobile_order: true },
   { id: 47, name: 'ポップコーンワゴン（ソアリン前）', category: 'restaurant', area:'mediterranean_harbor', pp: true },

   { id: 48, name: 'S.S.コロンビア・ダイニングルーム', category: 'restaurant', area:'american_waterfront' },
   { id: 49, name: 'ケープコッド・クックオフ', category: 'restaurant', area:'american_waterfront', mobile_order: true },
   { id: 50, name: 'ケープコッド・クックオフ（ショーレストラン）', category: 'restaurant', area:'american_waterfront' },
   { id: 51, name: 'ケープコッド・コンフェクション', category: 'restaurant', area:'american_waterfront' },
   { id: 52, name: 'ドックサイドダイナー', category: 'restaurant', area:'american_waterfront', mobile_order: true },
   { id: 53, name: 'テディ・ルーズベルト・ラウンジ', category: 'restaurant', area:'american_waterfront' },
   { id: 54, name: 'テディ・ルーズベルト・ラウンジテラス席', category: 'restaurant', area:'american_waterfront' },
   { id: 55, name: 'デランシー・ケータリング', category: 'restaurant', area:'american_waterfront' },
   { id: 56, name: 'ニューヨーク・デリ', category: 'restaurant', area:'american_waterfront', mobile_order: true },
   { id: 57, name: 'バーナクル・ビルズ', category: 'restaurant', area:'american_waterfront' },
   { id: 58, name: 'ハイタイド・トリート', category: 'restaurant', area:'american_waterfront' },
   { id: 59, name: 'ハドソンリバー・ハーベスト', category: 'restaurant', area:'american_waterfront', mobile_order: true },
   { id: 60, name: 'パパダキス・フレッシュフルーツ', category: 'restaurant', area:'american_waterfront' },
   { id: 61, name: 'リバティ・ランディング・ダイナー', category: 'restaurant', area:'american_waterfront' },
   { id: 62, name: 'レストラン櫻', category: 'restaurant', area:'american_waterfront', mobile_order: true },
   { id: 63, name: 'レストラン櫻テラス席', category: 'restaurant', area:'american_waterfront' },
   { id: 64, name: 'ポップコーンワゴン（ケープコッド・クックオフ前）', category: 'restaurant', area:'american_waterfront' },
   { id: 65, name: 'ポップコーンワゴン（ドックサイドステージ前）', category: 'restaurant', area:'american_waterfront' },
   { id: 66, name: 'ポップコーンワゴン（リドアイル前）', category: 'restaurant', area:'american_waterfront' },
   { id: 67, name: 'ポップコーンワゴン（リバティ・ランディング・ダイナー前）', category: 'restaurant', area:'american_waterfront' },
   { id: 68, name: '', category: 'restaurant', area:'american_waterfront' },

   { id: 69, name: 'シーサイドスナック', category: 'restaurant', area:'port_discovery' },
   { id: 70, name: 'ブリーズウェイ・バイツ', category: 'restaurant', area:'port_discovery' },
   { id: 71, name: 'ベイサイド・テイクアウト', category: 'restaurant', area:'port_discovery' },
   { id: 72, name: 'ホライズンベイ・レストラン', category: 'restaurant', area:'port_discovery' },
   { id: 73, name: 'ポップコーンワゴン（アクアトピア横）', category: 'restaurant', area:'port_discovery' },

   { id: 74, name: 'エクスペディション・イート', category: 'restaurant', area:'lost_river_delta' },
   { id: 75, name: 'トロピック・アルズ', category: 'restaurant', area:'lost_river_delta' },
   { id: 76, name: 'ミゲルズ・エルドラド・キャンティーナ', category: 'restaurant', area:'lost_river_delta', mobile_order: true },
   { id: 77, name: 'ユカタン・ベースキャンプ・グリル', category: 'restaurant', area:'lost_river_delta', mobile_order: true },
   { id: 78, name: 'ユカタン・ベースキャンプ・グリル（テイクアウトカウンター）', category: 'restaurant', area:'lost_river_delta', mobile_order: true },
   { id: 79, name: 'ロストリバークックハウス', category: 'restaurant', area:'lost_river_delta' },
   { id: 80, name: 'ポップコーンワゴン（ハンバーステージ横）', category: 'restaurant', area:'lost_river_delta' },

   { id: 81, name: 'アレンデール・ロイヤルバンケット', category: 'restaurant', area:'fantasy_springs', mobile_order: true },
   { id: 82, name: 'オーケンのオーケーフード', category: 'restaurant', area:'fantasy_springs' },
   { id: 83, name: 'スナグリーダックリング', category: 'restaurant', area:'fantasy_springs', mobile_order: true },
   { id: 84, name: 'ルックアウト・クックアウト', category: 'restaurant', area:'fantasy_springs', mobile_order: true },
   { id: 85, name: 'ポップコーンワゴン（フェアリー・ティンカーベルのビジーバギー前）', category: 'restaurant', area:'fantasy_springs' },

   { id: 86, name: 'オープンセサミ', category: 'restaurant', area:'arabian_coast' },
   { id: 87, name: 'カスバ・フードコート', category: 'restaurant', area:'arabian_coast', mobile_order: true },
   { id: 88, name: 'サンタンズ・オアシス', category: 'restaurant', area:'arabian_coast' },
   { id: 89, name: 'ポップコーンワゴン（アラビアンコースト前）', category: 'restaurant', area:'arabian_coast' },

   { id: 90, name: 'セバスチャンのカプリソキッチン', category: 'restaurant', area:'mermaid_lagoon', mobile_order: true },
   { id: 91, name: 'ポップコーンワゴン（コーヴ・オブ・ワンダー前）', category: 'restaurant', area:'mermaid_lagoon' },
   { id: 92, name: 'ポップコーンワゴン（スカットルのスクーター前）', category: 'restaurant', area:'mermaid_lagoon' },

   { id: 93, name: 'ヴォルケイニア・レストラン', category: 'restaurant', area:'mysterious_island' },
   { id: 94, name: 'ノーチラスギャレー', category: 'restaurant', area:'mysterious_island', mobile_order: true },
   { id: 95, name: 'リフレッシュメント・ステーション', category: 'restaurant', area:'mysterious_island' },
 ]

 include ActiveHash::Associations
 has_many :plan_steps
 
end